server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customerapi
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/customerapi/**
eureka:
  client:
    register-with-eureka: false
management:
  tracing:
    sampling:
      probability: 1.0